leg100/otf

- http/state_version.go
- http/workspace.go
- http/workspace_test.go
- mock/workspace.go
- sqlite/state_version.go
- sqlite/state_version_output.go
- sqlite/workspace.go
- sqlite/workspace_test.go
- state_version.go
- state_version_list.go
- state_version_output.go
- workspace.go
It's better to use the structs from the hashicorp maintained go-tfe repo. We can then leverage ongoing updates to those structs which likely (?) reflect changes in the terraform bin.
> Use upstream structs where possible

- http/org_test.go
- org.go
- sqlite/org.go
We support state storage, so we should say so when asked for list of entitlements.
> Update state storage entitlement

- http/helpers.go
- http/workspace.go
Return a 409 Conflict when workspace is already locked/unlocked.
> Return conflict error when already locked/unlocked

- agent/agent.go
- agent/agent_test.go
- agent/processor.go
- agent/processor_test.go
- cmd/otsd/main.go
- go.mod
- go.sum
- http/org_test.go
- http/server.go
- http/workspace_test.go
- sqlite/configuration_version_test.go
- sqlite/org_test.go
- sqlite/sqlite.go
- sqlite/state_version_test.go
- sqlite/workspace_test.go
Log messages via the [logr](https://github.com/go-logr/logr) interface.
And adds a `--log-level` CLI flag.
> Log via logr interface

- sql/migrations/000002_insert_organization_default.sql
Pre-configure oTF with a default organization, `default`, to save the user from having to create one.
> Default org

- agent/environment.go
- e2e/tasks.go
- errors.go
- hack/go-tfe-tests.bash
- http/html/static/css/main.css
- http/html/static/templates/content/workspace_edit.tmpl
- otf.go
- workspace.go
- workspace_factory_test.go
OTF relies on at least one feature that is only supported in version 1.2.0 of terraform and higher: setting credentials in TF_TOKEN_* environment variables.
Setting a relatively recent version as the minimum also makes it easier to develop and test OTF.
> Set min supported terraform version (1.2.0)

- e2e/lock_file_test.go
- run.go
If user has not uploaded a lock file then OTF produces an error
```
Error: reading lock file: open /tmp/otf-config-65329753/subdir/.terraform.lock.hcl: no such file or directory
```
But there are legitimate cases in which a user may not upload a lock file, e.g. no resources but only variables.
> Terraform lock file is optional

- http/html/workspace.go
#299 reveals speculative runs on the run listing for a workspace on the web UI, however the watch endpoint is still filtering out speculative runs, so the run listing page does not receive automatic updates.
This PR removes that filter.
> Watch speculative runs too

- agent/environment.go
- agent/environment_test.go
Fixes a bug @fsaintjacques found: the `terraform.tfvars` file containing variables is written to the configuration directory *root*, whereas it should be written to the *working directory*.
> Fix variable with custom workdir bug

- github/client.go
- github/test_server.go
- sql/migrations/20230224094530_add_team_name_constraint_not_null.sql
- sql/team_test.go
...also, for github team synchronisation, we've been using the github team name, which often contains whitespace and mixed capitalization, whereas in OTF, we should not be using either for names anywhere (OTF names *are* slugs, and vice-versa). Therefore, use the github team *slug* for synchronisation instead.
> Team name is mandatory

- go.mod
Would like to use the new 1.20 feature that permits wrapping multiple errors.
> Bump go to 1.20

- cmd/environment_variables.go
- cmd/otf-agent/main.go
- cmd/otf/app.go
- cmd/otfd/main.go
- docs/index.md
This PR adds support for env vars suffixed with `_FILE`. This allows for one to set e.g. `OTF_SECRET_FILE` to a file path, which OTF will read, and assign it to the `--secret` argument.
This is useful for some container environments where secrets can only be mounted and are expected to be read by the application itself. This is also more secure, as env vars are trivial to be read by anyone who has access to the host. This way, files can be permissioned, and the values can be only known by the user running the application, and thus the application itself.
I've also added some docs to explain this, as I had to dig into the code to see that env var configuration is supported.
> Add support for _FILE env vars

- app/app.go
- http/workspace.go
- sql/workspace.go
- workspace.go
- workspace/connector.go
- workspace_connector.go
- Introduce the function CreateWorkspace that creates both the workspace resource and potentially tries to connect it immediately (inside a transaction) if a repository was provided.
- Fixed newChildApp to make the Authorizer use the transaction.
- Added support to specify a branch for the repository.
> Add support for attaching a VCS in CreateWorkspace

- otf.go
- run/reporter.go
- scheduler/scheduler.go
- sql/db.go
- sql/db_test.go
If the run scheduler restarts (as a result of an error, which can happen as part of the normal flow, particularly in integration tests), then it should release the session-level advisory lock it holds in postgres. However, it was not doing that and as a result when it restarted it could not re-obtain the lock.
(This bug *might* be the cause of #334 and #338, although in both cases it doesn't seem like the scheduler was being restarted, otherwise the logs would have reported that quite clearly).
> Fix session level advisory locks

- auth/db_row.go
- auth/user_db.go
- auth/user_service.go
- cmd/otfd/main.go
- daemon/daemon.go
- integration/helper_test.go
- integration/user_test.go
- sql/pggen/user.sql.go
- sql/queries/user.sql
Any users promoted to site admin, using `--site-admins=`, are, with this PR, now created if they don't exist before being promoted.
> Auto-create nominated site admins

- integration/logs_test.go
- logs/proxy.go
The caching of logs is an asynchronous operation and thus the integration test for retrieval of logs would occasionally receive only the first chunk, and not both as expected. This PR fixes by simply writing a single chunk for the test, since the test in question if testing the retrieval and not the persistence of logs.
> Fix flaky logs test

- auth/user.go
- auth/user_test.go
- integration/organization_test.go
- organization/db.go
- organization/organization.go
- run/spawner.go
Fixes a bug wherein a new user can list all organizations until they create their first organization.
> fix: new users see all orgs

- Makefile
- api/state.go
- api/state_marshaler.go
- api/types/state.go
Fixes #421 
Also:
* fixes marshaling of outputs when included alongside a state version.
* runs latest upstream `go-tfe` API tests against the state version outputs API
> Fix up state version output API

- internal/http/html/static/templates/content/workspace_get.tmpl
- internal/integration/organization_min_permissions_test.go
- internal/integration/plan_permission_e2e_test.go
- internal/integration/test_daemon.go
- internal/rbac/role.go
- internal/workspace/web.go
Fixes #426 and addresses a few other issues for users with limited privileges:
* Removes the option to "plan and apply" a run from the UI for a user who can only plan a run.
* Adds some tests demonstrating a user receives miminum permissions across an organization
* A user with the read role can now tail a run, so they see logs in real time via the UI
> Fix workspace access for unprivileged user

- internal/cloud/client.go
- internal/github/client.go
- internal/github/test_server.go
- internal/gitlab/client.go
- internal/repo/db.go
- internal/repo/hook.go
- internal/repo/repo.go
- internal/repo/service.go
- internal/repo/synchroniser.go
- internal/repo/synchroniser_test.go
- internal/repo/test_helpers.go
- internal/sql/pggen/agent_token.sql.go
- internal/sql/pggen/webhook.sql.go
- internal/sql/queries/webhook.sql
- internal/workspace/service.go
- internal/workspace/tag_db.go
Fixes a couple of issues with webhooks. Upon "connecting" a workspace with a repo, OTF checks to see if a webhook is already configured for the repo, and if so, it checks for any discrepancies in its configuration, and if there are discrepancies then it updates the webhook configuration to bring into sync with what OTF has. However, that code had a bug where even though the configuration was ok it would flag up a discrepancy and so the webhook would always be updated.
Secondly, the Github client code for updating a webhook would neglect to set all the required parameters. Specifically, it neglected to set the "content-type" of the webhook payload, and thus Github would revert to its default, `form`, whereas OTF requires it to be set to `json`.
This fix does two things:
1. Don't check for …
> fix: webhook updates

- internal/configversion/tarball_service.go
- internal/inmem/cache.go
- internal/logs/proxy.go
- internal/run/lock_file_service.go
- internal/run/service.go
- internal/state/service.go
If the cache fails for whatever reason it should not be a fatal error, i.e. it should not stop the terraform operation from proceeding.
Fixes #453
> fix: caching failures are non-fatal

- Makefile
fix #427 
This fixes the makefile rule for me on macOS and it also (still) works on Linux.
> Use `mktemp` instead of `tempdir`

- internal/api/run.go
- internal/api/types/run.go
- internal/configversion/service.go
- internal/http/html/static/templates/content/workspace_edit.tmpl
- internal/http/html/static/templates/content/workspace_get.tmpl
- internal/integration/connect_repo_e2e_test.go
- internal/integration/plan_permission_e2e_test.go
- internal/integration/run_test.go
- internal/integration/start_run_ui_test.go
- internal/integration/ui_actions.go
- internal/run/db.go
- internal/run/factory.go
- internal/run/factory_test.go
- internal/run/run.go
- internal/run/run_test.go
- internal/run/spawner.go
- internal/run/starter.go
- internal/run/starter_test.go
- internal/run/test_helpers.go
- internal/run/web.go
- internal/run/web_test.go
- internal/scheduler/queue.go
- internal/scheduler/queue_test.go
- internal/sql/migrations/20230613192456_add_plan_only_column_to_runs.sql
- internal/sql/pggen/agent_token.sql.go
- internal/sql/pggen/run.sql.go
- internal/sql/queries/run.sql
Adds support for the specifying the `plan-only` attribute when creating a run via the API:
https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#create-a-run
This overrides the `speculative` attribute when specified on the configuration version for the run.
Note: throughout TFC documentation, both "speculative" and "plan-only" are used to refer to the same thing: a run that only performs a plan and does not follow through to an apply. I think Hashicorp are increasingly using the latter term, "plan-only", because it is more descriptive. I've followed suit in this PR and updated the OTF codebase to use variants of the latter term and minimise references to "speculative" runs.
> feat: support creating plan-only runs

- internal/http/html/static/templates/content/run_listing.tmpl
- internal/integration/run_list_ui_test.go
- internal/integration/workspace_ui_test.go
Real-time updates to the run listing on the UI were broken by an incorrect template name.
* Fixes this
* Adds browser-based test
> fix: real-time run listing updates

- internal/http/server.go
`/healthz` no longer reveals commit, build, and version info, but just prints `{"status":"OK"}`.
A new endpoint, `/version`, now includes the above info.
> fix!: don't reveal info on healthz endpoint

- hack/go-tfe-tests-upstream.bash
- hack/go-tfe-tests.bash
- internal/api/api.go
- internal/api/marshaler.go
- internal/api/team_marshaler.go
- internal/api/team_membership.go
- internal/auth/client.go
- internal/auth/team_web.go
- internal/auth/user_db.go
- internal/auth/user_service.go
- internal/cli/team.go
- internal/cli/team_test.go
- internal/daemon/daemon.go
- internal/integration/organization_min_permissions_test.go
- internal/integration/plan_permission_e2e_test.go
- internal/integration/team_cli_test.go
- internal/integration/user_test.go
- internal/integration/web_test.go
- internal/integration/write_permission_e2e_test.go
- internal/orgcreator/service.go
- internal/sql/pggen/agent_token.sql.go
- internal/sql/pggen/team_membership.sql.go
- internal/sql/queries/team_membership.sql
Fixes #490 
Makes a breaking change to two CLI commands, permitting more than one user to be added/removed to/from a team:
`otf teams add-user [username]` -> `otf teams add-users [username|...]`
`otf teams del-user [username]` -> `otf teams del-users [username|...]`
Adds support for the following `tfe` provider resources:
* `tfe_team_member`
* `tfe_team_members`
> feat!: add team membership tfe api endpoints

- hack/go-tfe-tests-upstream.bash
- internal/api/api.go
- internal/api/marshaler.go
- internal/api/oauth_client.go
- internal/api/oauth_client_marshaler.go
- internal/api/types/oauth_client.go
- internal/api/types/oauth_token.go
- internal/daemon/daemon.go
Fixes #491 
Note: only adds support for Github for these endpoints. If using the `tfe` provider, then the following parameters are expected at minimum for the `tfe_oauth_client` resource:
```terraform
resource "tfe_oauth_client" "test" {
api_url          = "https://api.github.com"
http_url         = "https://github.com"
service_provider = "github"
}
```
> feat: add tfe-api OAuth Client endpoints

- Makefile
- hack/go-tfe-tests-upstream.bash
- internal/api/marshaler.go
- internal/api/team.go
- internal/api/team_marshaler.go
- internal/api/types/pagination.go
- internal/api/types/team.go
- internal/auth/client.go
- internal/auth/db_row.go
- internal/auth/team.go
- internal/auth/team_db.go
- internal/auth/team_service.go
- internal/auth/team_test_helpers.go
- internal/auth/team_web.go
- internal/auth/user.go
- internal/cli/team.go
- internal/cli/test_helpers.go
- internal/client/client.go
- internal/http/html/static/templates/content/team_get.tmpl
- internal/integration/daemon_helpers_test.go
- internal/integration/team_service_test.go
- internal/integration/web_test.go
- internal/orgcreator/service.go
- internal/sql/migrations/20230630180152_add_tfe_columns_to_team.sql
- internal/sql/pggen/agent_token.sql.go
- internal/sql/pggen/team.sql.go
- internal/sql/queries/team.sql
- internal/sql/sql.go
This PR introduces everything necessary to ensure OTF passes the integration tests for the Teams API. This includes:
* adding further Teams API endpoints to complete the [documented list](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/teams)
* adding a bunch of fields to the `Team` type and persisting them to the database, even though OTF doesn't support them (yet).
This also means OTF supports the `tfe` provider's `tfe_team` resource (unsupported fields aside).
> feat: pass go-tfe team integration tests

- internal/auth/team_db.go
- internal/auth/user_service.go
- internal/integration/user_test.go
Owners team cannot be empty. OTF did prevent this, but didn't account for the scenario in which _multiple_ team members are deleted at once.
> fix: prevent empty owners team

- internal/workspace/workspace.go
The following bumps the default version to v1.5.2.
> chore: Bump default terraform version to v1.5.2

- docs/rbac.md
- internal/auth/team_web.go
- internal/auth/user.go
- internal/auth/user_service.go
- internal/http/html/html.go
- internal/http/html/static/css/output.css
- internal/http/html/static/templates/content/team_get.tmpl
- internal/http/html/static/templates/content/workspace_get.tmpl
- internal/http/html/static/templates/partials/search_dropdown.tmpl
- internal/integration/tag_e2e_test.go
- internal/integration/team_ui_test.go
- internal/integration/user_test.go
- internal/rbac/role.go
- internal/workspace/web.go
This PR changes the behaviour of the add team member functionality, both via the UI and the API: when adding a user to a team, if the user does not exist the user is created.
This is a deviation from TFC's behaviour. But then OTF already differs quite a bit from TFC when it comes to users: in OTF, users are not "invited" and are instead created the first time they login. There is no email functionality because that would add a further dependency (a mail relay).
> feat!: adding team member creates user if they don't exist

- go.mod
- go.sum
- internal/agent/agent.go
- internal/agent/environment.go
- internal/agent/executor.go
- internal/agent/steps.go
- internal/agent/terraform_download.go
- internal/agent/terraform_downloader.go
- internal/agent/terraform_downloader_test.go
- internal/agent/terraform_path_finder.go
- internal/integration/daemon_helpers_test.go
- internal/integration/helpers_test.go
- internal/integration/main_test.go
- internal/integration/tag_e2e_test.go
- internal/integration/terraform_cli_cancel_test.go
- internal/integration/terraform_cli_discard_test.go
- internal/integration/terraform_login_test.go
Integration tests now always use the configured default version of terraform, rather than whatever terraform happens to be at the front of PATH.
fix: race condition between writing downloaded terraform binary and setting file permissions.
> refactor: always test against default terraform

- internal/api/run.go
- internal/api/types/run_event.go
`terraform plan|apply` as of v1.5 sends a request to `/api/v2/runs/<run_id>/run-events` if using the `cloud` backend. OTF did not handle this request and hence terraform would error with `resource not found`.
This PR stubs this endpoint, returning an empty response, which works around the issue.
(Run events would usually be warnings about various policy issues OTF doesn't implement anyway).
> fix: handle run-events request from terraform cloud backend

- internal/auth/team_web.go
- internal/http/html/functions.go
- internal/http/html/renderer.go
- internal/http/html/static/css/output.css
- internal/http/html/static/templates/content/module_list.tmpl
- internal/http/html/static/templates/content/organization_edit.tmpl
- internal/http/html/static/templates/content/organization_get.tmpl
- internal/http/html/static/templates/content/team_get.tmpl
- internal/http/html/static/templates/content/team_list.tmpl
- internal/http/html/static/templates/content/variable_list.tmpl
- internal/http/html/static/templates/content/workspace_edit.tmpl
- internal/http/html/static/templates/content/workspace_get.tmpl
- internal/http/html/static/templates/content/workspace_list.tmpl
- internal/http/html/static/templates/partials/variable_form.tmpl
- internal/http/html/static/templates/partials/workspace_header_links.tmpl
- internal/module/web.go
- internal/module/web_test.go
- internal/organization/web.go
- internal/run/test_helpers.go
- internal/run/web.go
- internal/run/web_test.go
- internal/variable/web.go
- internal/workspace/web.go
- internal/workspace/web_test.go
Hide rather than show and disable.
Fixes #540
> feat(ui): hide functionality from unpriv persons

- internal/http/html/static/templates/partials/run_item.tmpl
- internal/integration/run_test.go
- internal/run/db.go
- internal/run/factory.go
- internal/run/run.go
- internal/run/run_test.go
- internal/sql/migrations/20230802183439_add_created_by_user_to_runs.sql
- internal/sql/pggen/agent_token.sql.go
- internal/sql/pggen/run.sql.go
- internal/sql/queries/run.sql
And add their username to the run widget on the UI.
> feat: record who created a run

- internal/http/html/static/templates/content/workspace_get.tmpl
- internal/integration/run_api_test.go
- internal/integration/run_test.go
- internal/run/factory.go
- internal/run/factory_test.go
- internal/run/run.go
- internal/run/web.go
- internal/workspace/workspace.go
@fsaintjacques A heads up - I recall removing the magic string behaviour from your software, so I'm pretty sure this is now safe to remove from OTF.
(If you recall, when creating a run, we wanted the run to automatically fetch the config from the git repo, so we introduced a magic string to invoke this behaviour. But then I realised you could simply leave out the configuration version ID from CreateRun and that invokes the same behaviour).
> chore: remove redundant CreateRun magic string

- .github/workflows/build.yml
- internal/integration/main_test.go
https://github.com/chromedp/chromedp/issues/1325#issuecomment-1666372303
> chore: chromium bug fixed

- internal/workspace/web.go
Closes #579
Use the `.Name` of the workspace as the page `<title>` instead of the `ID`, for friendly viewing.
The `.ID` is still available in both the URL and on the page of the workspace
> Make workspace page title use Name, not ID

- internal/logs/proxy.go
- internal/notifications/notifier.go
- internal/pubsub/broker.go
- internal/repo/purger.go
- internal/run/reporter.go
- internal/scheduler/scheduler.go
Fixes #577 
The events broker can legitimately terminate the subscription of a subscriber, e.g. when the subscriber's event queue is full up. Various subsystems such as the scheduler would, in such a scenario, simply shutdown. Which in the case of #577 would mean no more runs could be started.
This PR changes the behaviour of the subsystems: when their subscription is terminated, they instead return an error, which triggers the subsystem to be restarted (using a backoff algorithm) rather than stop completely.
> fix: resubscribe subsystems when their subscription is terminated

- internal/state/tfe.go
- internal/tfeapi/types/workspace.go
- internal/workspace/tfe.go
> fix: tfe_outputs resource

- internal/agent/spooler.go
- internal/agent/spooler_test.go
- internal/daemon/daemon.go
- internal/daemon/subsystem.go
- internal/daemon/subsystem_test.go
Fixes #577 (again). The original fix, #593, left out the agent spooler system, which is responsible for relaying run events to the agent. So when its subscription was terminated, it didn't restart itself.
This PR changes that: the spooler will now restart itself whenever its subscription is terminated.
> fix: restart spooler when broker terminates subscription

- internal/agent/terraform_downloader_test.go
- internal/authenticator/oidc_authenticator.go
- internal/cloud/config.go
- internal/configversion/tfe_test.go
- internal/github/client.go
- internal/http/transport.go
- internal/run/client.go
This PR does two main things, 
In areas where we manually construct an http.Transport unless we explicitly provide a Proxy field of http.ProxyFromEnvironment, we are explicitly configuring the http package to ignore the proxy environment variables. This means that otf ignores all proxy settings.
Changes the oidc_authenticator to ensure that it throws an error after waiting for more than ten seconds to construct the oidc provider. This "fix" is intended to keep the tool silently waiting when the proxy settings are ommitted (or other network issues are blocking in the NewProvider func)
> fix: fixed bug where proxy was ignored

- internal/module/web.go
This PR prevent modules with no published versions from triggering a nil panic.
> fix: prevent modules with no published versions from crashing otf

- internal/integration/github_app_test.go
- internal/integration/terraform_cli_cancel_test.go
- internal/releases/releases.go
Note: a regression appears to be present in 1.6.2 that was not present in 1.5.x: if a `terraform plan` is a mid-flow and the user sends the process a ctrl-c signal, the process exits without canceling the run on TFC/OTF. However, this regression only appears to impact `terraform plan` and not `terraform apply`.
Another note: one of the integration tests for the recently added github app was improperly implemented and would transiently fail. In order to get this PR through, I've fixed it here.
> Bump default terraform version to 1.6.2

- internal/run/reporter.go
- internal/run/reporter_test.go
> fix: skip reporting runs created via API

- internal/integration/run_error_test.go
- internal/run/api.go
- internal/run/phase.go
- internal/state/service.go
Fixes #626.
#625 broke the OTF API endpoint for creating a state version, which is used by the agent to create and upload state. Fortunately this regression was only introduced recently and did not get released.
#625 introduced another regression to the OTF API endpoint responsible for finishing a run phase, which again is used by the agent. The regression in particular resulted in errors failing to be reported, which meant the first bug didn't get captured by the integration tests.
This PR addresses these bugs and adds an integration test specifically for run errors.
> fix: agent error reporting

- internal/variable/variable.go
- internal/variable/variable_test.go
This PR resolves #630 by using heredocs in variables when that variable includes a newline. 
This PR isn't intended to fix all escaping with the WriteTerraformVars function, and there are other ways that this can be broken (for example using backspaces and double quotes within the value of the variable)
> fix: fixed defect with multiline tfvars not being escaped

- internal/rbac/role.go
- internal/rbac/role_test.go
We have encountered the issue that a team member with permission to manage workspace cannot cancel a pending run. This PR adds the missing `CancelRunAction` to the `WorkspaceWriteRole`.
> fix: Add missing CancelRunAction to WorkspaceWriteRole

- internal/agent/daemon.go
- internal/agent/job.go
- internal/agent/job_test.go
- internal/agent/service.go
- internal/agent/web.go
- internal/http/html/static/templates/content/agent_pools_list.tmpl
- internal/http/html/static/templates/content/agent_pools_list_allowed.tmpl
- internal/http/html/static/templates/content/workspace_edit.tmpl
- internal/workspace/web.go
* Workspace agent pool select form would incorrectly show current agent pool when there are multiple pools
* Jobs could incorrectly transition state, e.g. from canceled to allocated
* Agent would, upon failing to start an allocated job, re-attempt to start the job repeatedly without backing off
> fix: various agent pool and job bugs

- internal/integration/organization_token_test.go
- internal/organization/db.go
- internal/organization/service.go
- internal/organization/web.go
- internal/sql/pggen/agent.sql.go
- internal/sql/pggen/organization_token.sql.go
- internal/sql/queries/organization_token.sql
- internal/tokens/middleware.go
- internal/tokens/middleware_test_helpers.go
- internal/tokens/service.go
Organization tokens have been broken since they were refactored in 104013d4. The JWT contains the _organization token_ _ID_ but the middleware was checking the _organization_ _name_.
Might fix #658.
> fix: organization tokens

- internal/agent/allocator.go
- internal/agent/allocator_test.go
Fixes an issue whereby everytime a job runs the allocator service would restart.
> fix: allocator restarting unnecessarily

- internal/scheduler/queue.go
- internal/scheduler/scheduler.go
- internal/workspace/lock_db.go
The scheduler ensures only one run on each workspace is permitted to be running (the exception to this rule are "plan-only" runs, which we won't discuss here). A run begins in the `pending` state. It cannot transition to the next state, `plan_queued`, until:
(a) any other pending runs created before it have finished.
(b) its workspace is unlocked.
Once both conditions are true, the scheduler does the following:
(a) locks the workspace 
(b) updates the status of the run to `plan_queued`
(c) sets the run as the "current run" of the workspace
Once a run finishes it is also responsible for unlocking the workspace once a run completes. One of the bugs identified by the user is a race condition that occurs whenever a run finishes and its workspace is immediately deleted (this is not an …
> fix: don't unnecessarily restart scheduler

- internal/pubsub/broker.go
Set `OTF_SUB_BUFFER_SIZE` to an integer. Defaults to 100.
> feat: allow subscription buffer size to be overridden

- internal/daemon/daemon.go
- internal/github/client.go
- internal/integration/connect_repo_e2e_test.go
- internal/run/reporter.go
- internal/run/reporter_test.go
- internal/vcs/status.go
#685 reports the Github limit of 1000 commit status updates being routinely hit.
This PR does too things to avoid this limit being hit:
*  ensures the same status update is not sent more than once, thanks to the use of a cache.
* removes the `running` abstract VCS status, for which Github has no equivalent, and is not actually used anywhere else in OTF
> fix: avoid hitting Github limit on commit status updates

- internal/configversion/tfe.go
- internal/daemon/config.go
- internal/daemon/daemon_test.go
- internal/errors.go
- internal/http/decode/decoders.go
- internal/notifications/config.go
- internal/notifications/tfe.go
- internal/run/tfe.go
- internal/state/tfe.go
- internal/state/version.go
- internal/team/team.go
- internal/tfeapi/errors.go
- internal/variable/tfe.go
- internal/vcsprovider/tfe.go
- internal/workspace/tfe.go
- internal/workspace/workspace.go
Matches documented HCP Terraform API spec:
https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run#cancel-a-run
> fix: report 409 when cancel or force cancel not allowed

- internal/daemon/daemon.go
- internal/run/metrics.go
- internal/run/metrics_test.go
- internal/run/service.go
Adds metrics for total runs by status:
```
otf_runs_statuses{status="applied"} 0
otf_runs_statuses{status="apply_queued"} 0
otf_runs_statuses{status="applying"} 0
otf_runs_statuses{status="cost_estimated"} 0
otf_runs_statuses{status="pending"} 0
otf_runs_statuses{status="plan_queued"} 0
otf_runs_statuses{status="planning"} 1
```
> feat: run status metrics

- Makefile
- internal/http/html/static/css/output.css
- internal/http/html/static/templates/content/workspace_edit.tmpl
- internal/run/spawner.go
- internal/run/spawner_test.go
- internal/workspace/web.go
Currently OTF automatically triggers a speculative run i.e. a plan-only run for pull request events, when a PR is opened, when commits are pushed to the PR, etc.
This PR adds the option to disable this via the UI. It also adds the option to do so via the API (most of the plumbing was already there for the API for the purposes of satisfying the go-tfe integration tests, but it didn't actually do anything...).
> feat: add option to skip plans for pull requests

- cmd/otfd/main.go
- docs/docs/config/flags.md
- internal/daemon/config.go
- internal/daemon/daemon.go
- internal/http/html/components/websocket.go
- internal/http/html/components/websocket_list_handler.go
- internal/http/server.go
Fixes: #772
This gives otfd users a way to specify a comma-separated list of hostnames to validate websocket upgrade requests against.
Add a command-line parameter (`--allowed-origins`), add it to markdown docs, pass it through, split by commas, put the hostnames in a map, give `websocket.Upgrader` a callback to check for the Origin hostname's presence in the map.
A possible alternative would be to just return true in all cases.  That would make this patch much simpler; effectively a one-liner.
> Add --allowed-origins parameter

- internal/integration/variable_set_ui_test.go
- internal/variable/view.templ
- internal/variable/view_templ.go
When editing a variable set, the form has the wrong action URL.  Clicking the "Save" button results in a 404 error.
The form tries to submit to `.../edit`, but that's a GET endpoint.  The POST endpoint is `.../update`.  See the route definitions [here](https://github.com/leg100/otf/blob/master/internal/variable/web.go#L88-L89).
This patch fixes the form to submit to the right place.
> Fix the "Save variable set" button on the variableset edit page

- internal/runner/operation.go
- internal/runner/workdir.go
This fixes an issue with aws dynamic provider credentials.
A new tmpdir is created for each operation, so the absolute path for plan will be different than apply. The apply step uses the plan output, which means it doesn't read the inputs (I think?). Which means it wouldn't use the newly generated config/creds for the provider dynamic credentials and would try to look in the old path (which no longer existed).
The changing path also means that any files or values created during the plan will run into issues if they contain the absolute path. For example, the aws profile references another file by absolute path.
> fix: AWS dynamic provider credentials invalid apply absolute paths
