README.md, cmd/environment_variables.go, cmd/ots/client.go, cmd/ots/client_test.go, cmd/ots/credentials_store.go, cmd/ots/credentials_store_test.go, cmd/ots/login.go, cmd/ots/login_test.go, cmd/ots/main.go, cmd/ots/organization.go, cmd/ots/organization_new.go, cmd/ots/organization_new_test.go, cmd/otsd/main.go, cmd/signals.go, cmd/signals_test.go, go.mod
Adds a CLI command for creating organizations:
```bash
$ ots organizations new abc --email a.b.c@co
Successfully created organization abc
```
=> Add CLI command: ots organizations new

agent/agent.go, agent/agent_test.go, agent/job.go, agent/spooler.go, agent/spooler_mock.go, agent/spooler_test.go, app/run.go, cmd/otsd/main.go, events.go, run.go
No, not an FBI agent....
Introduces an event spooler into the agent, removing the need to poll for jobs.
=> Agent spooler

http/ansi_stripper.go, http/ansi_stripper_test.go, http/run.go
=> ANSI code stripper

http/run.go, http/server.go, run.go, sql/pggen/apply.sql.go, sql/pggen/run.sql.go, sql/queries/run.sql, sql/run.go, sql/run_test.go
=> Add global runs queue endpoint

apply.go, e2e/e2e_test.go, plan.go
=> Support terraform destroy

app/apply.go, run.go, run_test.go
=> Set apply unreachable status

app/run.go, run.go, run_factory.go, run_factory_test.go, sql/db.go, sql/run.go, sql/sql.go
=> Introduce service layer transactions

app/run.go, cache.go, modd.conf, plan.go, run.go, sql/migrations/000001_create_tables.sql, sql/pggen/apply.sql.go, sql/pggen/run.sql.go, sql/queries/run.sql, sql/run.go
=> Persist lockfile

app/app.go, cmd/otfd/main.go, events.go, hack/go-tfe-tests.bash, inmem/pub_sub.go, run.go, run_factory_test_helpers.go, sql/db.go, sql/pub_sub.go, sql/pub_sub_test.go, sql/run.go
One step towards allowing HA setup.
=> Use postgres as central pubsub broker

e2e/web_test.go, http/html/authenticator.go, http/html/authenticator_test.go, http/html/github.go, http/html/github_test.go, http/html/test_helpers.go
Create an owners team corresponding to owners of a github organization.
=> Github owners team

Makefile, cloud.go, cloud/cloud.go, cloud/user.go, e2e/cluster_test.go, e2e/connect_repo_test.go, e2e/daemon.go, e2e/module_test.go, e2e/plan_permission_test.go, e2e/sandbox_test.go, e2e/site_admin_test.go, e2e/start_run_ui_test.go, e2e/test_helpers.go, e2e/web_test.go, e2e/write_permission_test.go, github/client.go, github/client_test.go, github/event_handler.go, github/test_server.go, gitlab/client.go, gitlab/client_test.go, gitlab/test_server.go, http/html/authenticator.go, http/html/authenticator_test.go
An intermediate abstraction for dealing with user accounts on cloud providers.
=> Cloud user

cmd/otf/credentials_store.go, cmd/otf/credentials_store_test.go, e2e/cloud_block_test.go, http/server.go, modd.conf
=> Cloud block support

http/dto/run.go, http/run.go, run.go, run_factory.go, run_factory_test.go, run_factory_test_helpers.go, run_test.go, run_unmarshaller.go, sql/migrations/20230114150642_add_auto_apply_to_runs.sql, sql/pggen/agent_token.sql.go, sql/pggen/run.sql.go, sql/queries/run.sql, sql/run.go
=> Run auto apply

e2e/auto_apply_test.go, http/html/static/templates/content/workspace_edit.tmpl, http/html/workspace.go, sql/pggen/workspace.sql.go, sql/queries/workspace.sql, sql/workspace.go
=> Auto-apply

workspace.go
=> Fix unable to update ws repo

cmd/otfd/main.go, sql/db.go, sql/pggen/registry_session.sql.go, sql/registry_session.go, sql/registry_session_test.go, sql/session_test.go, sql/test_helpers.go, test_helpers.go
=> Clean registry session cleanup

http/html/static/css/main.css, http/html/static/images/cross.svg, http/html/static/images/hamburger.svg, http/html/static/templates/layout.tmpl
..and some flexbox wrapping too.
=> Hamburger menu for mobile

Makefile, e2e/connect_repo_test.go, e2e/daemon.go
* Give them more time to complete
* Cache providers
=> Make e2e tests more reliable

Makefile, app/module.go, app/module_version.go, http/html/module.go, http/html/static/templates/content/module_get.tmpl, module.go, module/publisher.go, publisher.go, sql/migrations/20230201113207_migrate_module_org_fk.sql, sql/module.go, sql/pggen/module.sql.go, sql/queries/module.sql, state/handlers.go, test_helpers.go, triggerer.go
...migrate it from org ID to org name. And unembed org from module.
=> Migrate module's org foreign key

http/html/run.go
=> Include speculative runs in listing

go.mod, http/html/paths/tools.go
=> Stop go mod tidy removing gen pkgs

Dockerfile, Dockerfile.agent, Makefile
Fixes #323 
And:
* Bump alpine base image version
* Don't cache alpine packages; reduces image size
=> Include git in docker image

.github/workflows/build.yml, Makefile, otf.go
#325 neglected to bump go in the CI/CD pipeline.
=> Fix warnings from staticcheck

e2e/variables_test.go, variable/test_helpers.go, variable/variable.go, variable/variable_test.go, variable/web.go, variable/web_test.go
=> Fix update of sensitive variables

auth/service.go, auth/user_service.go, integration/token_test.go, rbac/action.go, rbac/action_string.go
Adds authorization to the various user management endpoints that have recently been added:
* only site admins can add / remove users
* only org owners can add / remove users to / from the org
* only org owners can add / remove users to / from teams in the org
=> Authz for user management endpoints

auth/db_row.go, auth/user.go, auth/user_db.go, auth/user_service.go, cmd/otfd/main.go, daemon/config.go, daemon/daemon.go, sql/migrations/20230406182826_add_users_site_admin_column.sql, sql/pggen/agent_token.sql.go, sql/pggen/user.sql.go, sql/queries/user.sql
Necessary for bootstrapping a Google IAP deployment.
=> Add option to promote users to site admin

auth/web.go, daemon/daemon.go, daemon/daemon_test.go, errors.go, http/decode/decoders.go, http/jsonapi/errors.go, run/api.go, state/api.go
=> Report error when secret is unspecified

auth/web.go, configversion/api.go, daemon/daemon.go, http/html/static/css/main.css, http/html/static/templates/partials/run_item.tmpl, integration/terraform_cli_cancel_test.go, integration/terraform_cli_discard_test.go, integration/test_helpers.go, run/run.go, run/web.go
=> Fix discard and cancel of run via tf cli

sql/migrations/20230417181955_alter_workspace_run_cascade_delete_constraint.sql
=> Fix workspace run lock constraint cascade

repo/handler.go, repo/handler_test.go
=> fix: vcs event postgres publish error

.github/workflows/build.yml, Makefile, hack/go-tfe-tests.bash, workspace/api.go, workspace/client.go
=> feat: force unlock tfc api endpoint

http/html/static/js/main.js, http/html/static/templates/content/workspace_get.tmpl, http/html/static/templates/content/workspace_list.tmpl, http/html/static/templates/partials/resource_report.tmpl, http/html/static/templates/partials/run_item.tmpl, integration/ui_actions.go, run.go, scheduler/queue.go, scheduler/queue_test.go, sql/pggen/workspace.sql.go, sql/queries/workspace.sql, workspace/db.go, workspace/workspace.go
* add summary of planned changes to run widget
* add status of latest run to workspace widget
* update in real-time the run widget on the run page
Fixes #339 and #398.
=> feat: add plan summary to ui widget

internal/authz.go, internal/http/html/static/templates/content/workspace_edit.tmpl, internal/integration/workspace_permissions_service_test.go, internal/sql/pggen/agent_token.sql.go, internal/sql/pggen/workspace_permission.sql.go, internal/sql/queries/workspace_permission.sql, internal/workspace/permissions_db.go
=> chore: embed team ID in workspace policy

internal/http/html/paths/funcmap.go, internal/http/html/paths/gen.go, internal/http/html/paths/run_paths.go, internal/http/html/static/css/main.css, internal/http/html/static/js/main.js, internal/http/html/static/templates/content/run_actions.tmpl, internal/http/html/static/templates/content/run_get.tmpl, internal/http/html/static/templates/partials/run_actions.tmpl, internal/integration/configuration_version_test.go, internal/integration/events_test.go, internal/integration/notification_gcppubsub_test.go, internal/integration/notification_slack_test.go, internal/integration/retry_run_ui_test.go, internal/integration/run_complete_test.go, internal/integration/run_test.go, internal/integration/start_run_ui_test.go, internal/integration/test_daemon.go, internal/integration/test_helpers.go, internal/run/service.go, internal/run/web.go
=> feat: retry run via UI

docs/auth/providers/oidc.md
=> Fix: OIDC doc missing information on required scopes

docs/tfc_migration.md, mkdocs.yml
Fixes #297 
@pat-s Can you give this a proof-read and try it out? Thanks.
=> Migration guide

docs/config/flags.md, docs/dev.md, go.mod, go.sum, internal/http/html/livereload.go, internal/http/html/renderer.go, internal/http/html/renderer_dev.go, internal/http/html/renderer_embedded.go, internal/http/html/static.go, internal/http/html/static/templates/layout.tmpl, internal/http/server.go, modd.conf
=> feat: builtin livereload functionality

internal/http/server.go
Problem described in https://github.com/leg100/otf/issues/474
=> Add trailing slash to make path more compatible with TFC

internal/integration/run_api_test.go, internal/integration/run_test.go, internal/run/factory.go, internal/run/factory_test.go
Fixes: https://github.com/leg100/otf/issues/473
=> fix: run w/o config ID pull config from repo

internal/integration/notification_configuration_test.go, internal/notifications/config.go, internal/notifications/notifier.go, internal/notifications/notifier_test.go
=> fix: allow updating notification url

internal/http/server.go
=> fix: remove trailing slash from requests

internal/agent/worker.go, internal/api/run.go, internal/errors.go, internal/http/client.go, internal/run/client.go, internal/run/phase.go, internal/run/run.go, internal/run/service.go
Fixes https://github.com/leg100/otf/issues/486
=> fix: agent race error

internal/agent/steps.go
=> fix: terraform apply partial state updates

internal/http/html/static/css/input.css, internal/http/html/static/css/output.css, internal/http/html/static/templates/content/workspace_get.tmpl, internal/http/html/static/templates/content/workspace_list.tmpl, internal/http/html/static/templates/partials/workspace_item.tmpl
Adds tags to the workspace widget on the UI.
=> feat(ui): add tags to workspace widget

internal/authz.go, internal/http/html/static/templates/content/workspace_edit.tmpl, internal/integration/remote_state_sharing_test.go, internal/sql/pggen/workspace.sql.go, internal/sql/queries/workspace.sql, internal/tokens/run_token.go, internal/workspace/authorizer.go, internal/workspace/db.go, internal/workspace/permissions_db.go, internal/workspace/web.go, internal/workspace/workspace.go
=> feat: add support for terraform_remote_state

Makefile, internal/agent/executor.go, internal/api/cli.go, internal/api/configuration_version.go, internal/api/run.go, internal/api/workspace_marshaler.go, internal/http/html/static/css/input.css, internal/http/html/static/css/output.css, internal/http/html/static/templates/content/workspace_edit.tmpl, internal/integration/auto_apply_ui_test.go, internal/integration/daemon_helpers_test.go, internal/integration/helpers_test.go, internal/integration/workspace_allow_cli_apply_test.go, internal/integration/workspace_ui_test.go, internal/sql/migrations/20230806181842_add_workspace_allow_cli_apply.sql, internal/sql/pggen/workspace.sql.go, internal/sql/queries/workspace.sql, internal/strip_ansi.go, internal/workspace/db.go, internal/workspace/web.go, internal/workspace/workspace.go
=> feat: allow terraform apply on connected workspace

internal/http/html/static/templates/content/module_get.tmpl, internal/integration/module_test.go, internal/module/module.go, internal/module/publisher.go, internal/module/service.go, internal/module/web.go, internal/module/web_test.go
The module status was being set to 'pending' and then never updated.
* set non-pending statuses
* (ui): ensure module page still renders when setup fails or no tags are found
=> fix: set module status

hack/go-tfe-tests.bash, internal/variable/service.go, internal/variable/tfe.go
=> fix: variable set variables API

internal/variable/tfe.go
=> fix: dont scrub sensitive variable values for agent

Makefile, internal/configversion/service.go, internal/configversion/tfe.go, internal/configversion/tfe_test.go, internal/errors.go, internal/run/errors.go, internal/run/run.go, internal/run/run_test.go, internal/run/service.go, internal/scheduler/queue.go, internal/tfeapi/errors.go, internal/workspace/errors.go, internal/workspace/lock.go, internal/workspace/lock_db.go, internal/workspace/lock_test.go, internal/workspace/tfe.go, internal/workspace/workspace.go, internal/workspace/workspace_test.go
=> fix: log max config size exceeded

internal/agent/web.go, internal/resource/pagination.go, internal/resource/pagination_test.go
=> fix(ui): unresponsive agent pool page

internal/loginserver/view.templ, internal/loginserver/view_templ.go
=> Fix a bad background color on the oauth2 confirmation page
